---
# tasks file for ocs
- name: Include tasks for installation from source
  include_tasks: install_from_source.yml
  when: install_from_source|default(false) and not install_from_packages

- name: Include tasks for installation from packages
  include_tasks: install_from_packages.yml
  when: install_from_packages|default(true) and not install_from_source
