---
- name: Install EPEL repository
  package:
      name: epel-release
      state: present

- name: Install yum-utils to be able to enable remi programmatically
  package:
    name: yum-utils
    state: present

- name: Install the required packages in RedHat derivatives
  package:
    name: "{{ ocs_pkgreqs }}"
    state: installed
  tags:
    - ocs_pkgreqs
